# Generated by Django 3.0.8 on 2020-11-05 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201027_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlistUsers',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
